# _quarto.yml

project:
  type: default

format:
  html:
    embed-resources: true
    html-math-method: katex
    theme: lumen
    df-print: kable

execute:
  echo: false
  warning: false
  error: false
