---
title: "Lactate transport inhibition therapeutically reprograms fibroblast 
    metabolism in experimental pulmonary fibrosis"
    
authors:
- name: David R. Ziehr
  affiliations: 
  - ref: mgh
  - ref: bwh
  - ref: hms
- name: Nathan M. Krah
  affiliations:
  - ref: utah_gen
- name: Kevin Leahy 
  affiliations:
  - ref: bwh
- name: K. Mark Parnell
  affiliations:
  - ref: vettore
- name: Jack Varon
  affiliations: 
  - ref: bwh
  - ref: hms
- name: Rebecca M. Baron
  affiliations:
  - ref: bwh
  - ref: hms
- name: Nancy J. Philp
  affiliations:
  - ref: tj
- name: Lida P. Hariri
  affiliations: 
  - ref: hms
  - ref: mgh_path
- name: Edy Y. Kim
  affiliations:
  - ref: bwh
  - ref: hms
- name: Rachel S. Knipe
  affiliations:
  - ref: mgh
  - ref: hms
- name: Jared Rutter
  affiliations:
  - ref: utah_biochem
  - ref: utah_hhmi
- name: William M. Oldham
  affiliations:
  - ref: bwh
  - ref: hms
  email: woldham@bwh.harvard.edu
  corresponding: true
    
affiliations:
- id: mgh
  name: Department of Medicine, Massachusetts General Hospital, Boston, MA
- id: bwh
  name: Department of Medicine, Brigham and Women's Hospital and Harvard Medical School, Boston, MA
- id: hms
  name: Department of Medicine, Harvard Medical School, Boston, MA
- id: utah_gen
  name: Department of Human Genetics, University of Utah, Salt Lake City, UT
- id: vettore
  name: Vettore Biosciences, San Francisco, CA
- id: tj
  name: Department of Pathology, Anatomy & Cell Biology, Thomas Jefferson University, Philadelphia, PA
- id: mgh_path
  name: Department of Pathology, Massachusetts General Hospital, Boston, MA
- id: utah_biochem
  name: Department of Biochemistry, University of Utah, Salt Lake City, UT
- id: utah_hhmi
  name: Howard Hughes Medical Institute, University of Utah School of Medicine, Salt Lake City, UT 
  
format:
  docx:
    reference-doc: template.docx
    page-width: 7.5
    output-file: ziehr_2023_mcti_manuscript.docx
    fig-align: center
    
bibliography: 
- library.bib
- pkgs.bib
csl: jci.csl

crossref: 
  fig-title: ""
  title-delim: ""

filters:
- authors-block
---

```{r}
#| label: setup
#| include: false

# ensure refs are up-to-date
targets::tar_load(refs)
targets::tar_load(pkg_citations)

# load data for paper


# ensure figures are up-to-date
targets::tar_load(
  c(
    fig01,
    fig02,
    # fig03,
    # fig04,
    # fig05,
    # fig06,
    # fig10,
    # fig11,
    # resources_table,
    NULL
  )
)
```

\newpage

# Abstract 


# Keywords


\newpage

# Introduction

Idiopathic pulmonary fibrosis (IPF) is a chronic and progressive lung disease with high mortality and limited therapeutic options. IPF affects approximately 150,000 patients in the U.S. with a median survival of 3-5 years [@esposito2015; @raghu2016; @martinez2017]. Currently approved pharmacotherapies for IPF are limited to the antifibrotics pirfenidone and nintedanib that slow, but do not stop, disease progression [@king2014; @richeldi2014], leaving lung transplantation as the only option available to eligible patients with progressive disease. The limited efficacy of antifibrotic therapies emphasizes the need for novel therapeutic approaches targeting different features of IPF pathobiology.

Accumulating evidence suggests that metabolic reprogramming may be one such therapeutic vulnerability in IPF [@bueno2020; @selvarajah2021]. Lung fibrosis is driven by the excessive deposition of extracellular matrix by myofibroblasts [@martinez2017]. Fundamental changes in myofibroblast metabolism support myofibroblast differentiation and extracellular matrix production [@bernard2015; @xie2015; @goodwin2018; @hamanaka2019; @selvarajah2019]. In particular, increased glycolysis and lactate production have been observed in IPF myofibroblasts *ex vivo* and following TGF-β1 (TGFβ)-induced myofibroblast differentiation *in vitro* [@kottmann2012; @xie2015; @kottmann2015; @bernard2015]. These metabolic changes are critical for fibrogenesis, as small molecule inhibitors of glucose uptake, glycolysis, and lactate fermentation prevent myofibroblast differentiation *in vitro* and attenuate pulmonary fibrosis in animal models [@bernard2015; @kottmann2012; @xie2015; @goodwin2018; @judge2018; @cho2017]. Unfortunately, low target affinities, poor specificity, narrow therapeutic indices, and common genetic resistance have all hampered the translation of these investigational compounds for clinical use [@rodriguez-enriquez2009; @michelakis2017; @pelicano2006]. Moreover, the molecular mechanisms by which these metabolic inhibitors attenuate the myofibroblast differentiation transcriptional program remain unclear. In order to leverage metabolic therapies for IPF, more targeted and better characterized drugs must be developed.

Toward this end, we sought to characterize the effects of a novel metabolic approach - inhibition of lactate transport - on myofibroblast differentiation and experimental pulmonary fibrosis. Lactate must be secreted to sustain glycolysis in myofibroblasts. A family of monocarboxylate transporters (MCT1-4) maintains lactate homeostasis and small molecule inhibitors of these transporters have been under active clinical development for oncologic applications where glycolytic reprogramming also features prominently in disease pathobiology [@puri2020; @cluntun2021]. Importantly, compared to previously investigated inhibitors of glycolysis, MCT inhibitors exhibit favorable pharmacologic profiles and have successfully translated to human clinic trials [@halford2023]. Before the promise of this therapeutic approach in IPF may be realized, however, the preclinical efficacy and molecular mechanisms-of-action of lactate transport inhibitors must be demonstrated experimentally.

In this work, we evaluated the contribution of lactate transporters to experimental pulmonary fibrosis. We found increased expression of the lactate transporters MCT1 and MCT4 IPF patient lungs, consistent with increased glycolysis previously observed. Inhibition of these transporters attenuated bleomycin-induced lung fibrosis *in vivo* and TGFβ-induced myofibroblast differentiation *in vitro*, where MCT4 inhibition demonstrated increased therapeutic efficacy. *Using stable isotope tracing, high-resolution spatial metabolomics, we find...* Based on these findings, we report a novel MCT4 inhibitor suitable for human clinical studies. Together, these data illuminate a novel approach to disrupt the metabolic program fueling the exuberant fibrosis at the core of IPF and provide proof-of-concept to target lactate transporters in the treatment of this deadly disease. 

# Results

## MCT expression increases in human pulmonary fibrosis and experimental models

Of the four lactate transporters, MCT1 and MCT4 are the most highly expressed in the lung [@frangogiannis2020]. Based on this observation, we characterized MCT1 and MCT4 expression in human IPF lung explants obtained at the time of transplantation. Consistent with a pathologic role for MCT1 and MCT4 in IPF, we found significantly increased expression of these proteins in human IPF lung compared to non-fibrotic control samples (**Figure 1A-B**). These findings were recapitulated in experimental pulmonary fibrosis where intratracheal bleomycin increased both MCT1 and MCT4 expression (**Figure 1C-D**). 

A defining feature of IPF is the activation of tissue myofibroblasts, which are characterized by the *de novo* expression of smooth muscle α-actin (α-SMA); stress fiber formation; and increased migration, contraction, and extracellular matrix production [@selvarajah2021; @xie2015; @tomasek2002]. TGFβ is the most potent inducer of myofibroblast activation *in vitro* and *in vivo*. TGFβ-dependent α-SMA expression is a well-accepted and widely utilized model of myofibroblast activation relevant to pulmonary fibrosis [@goodwin2018; @cui2019; @rangarajan2018; @locy2020]. Consistent with our findings in human IPF lungs, we observed increased expression of MCT1 and MCT4 in normal human lung fibroblasts following TGFβ treatment (**Figure 1E-F**). These findings are consistent with increased expression of other glycolytic enzymes and the associated metabolic changes that have been previously observed in these cells [@xie2015]. Together, these data demonstrate that pulmonary fibrosis is associated with increased expression of lactate transporters in the lung generally and in myofibroblasts specifically. 

## Lactate transport is essential for myofibroblast differentiation *in vitro*

Using RNA interference and pharmacologic approaches, we next tested whether MCT expression and activity were required for myofibroblast differentiation *in vitro*. Lung fibroblasts were transfected with siRNA targeting MCT1 and MCT4 separately and together. After 24 h, the cells were treated with TGFβ for 48 h to induce myofibroblast differentiation. The siRNAs reduced lactate transporter protein levels > 80% (**Figure 2A-B**). Decreasing MCT1 or MCT4 expression caused a marked reduction in TGFβ-stimulated α-SMA expression. Notably, siMCT1 also decreased MCT4 expression. Interestingly, the mRNA sequence homology of these transporters is low and the MCT1 siRNA sequences do not match the MCT4 mRNA sequence, perhaps suggesting a post-translational explanation for this phenomenon. No adverse effects of lactate transporter knockdown on cell viability were observed, and siMCT1 significantly increased cell count in both control and TGFβ-treated cells (**Supplemental Figure 2A**). 

Given the reduction of MCT4 expression following siMCT1 treatment, we next evaluated the effects of pharmacologic MCT inhibitors on myofibroblast differentiation. AZD3965 is a high-affinity (*K~i~* 1.6 nM) inhibitor of MCT1 [@curtis2017]. VB124 is a recently developed high-affinity (IC~50~ 19 nM) inhibitor of MCT4 [@cluntun2021]. IPF lung fibroblasts were differentiated with TGFβ in the presence of these MCT inhibitors (**Figure 2C-D**). MCT4 inhibition by VB124 alone, or in combination with AZD3965, decreased Col1a1 and α-SMA expression. These effects were also observed in normal lung fibroblasts where AZD3965 as well as VB124, separately or together, decreased α-SMA expression (**Figure 2E-F**). AR-C155858, which is a high-affinity(*K~i~* 2 nM) inhibitor of both MCT1 and MCT2 [@ovens2010], also decreased α-SMA expression alone and in combination with VB124 (**Supplemental Figure 2B-C**). Pharmacologic MCT inhibition did not affect cell counts over 48 h of treatment (**Supplemental Figure 2D-E**). As anticipated, decreased Col1a1 and α-SMA expression was associated with decreased myofibroblast contractility as assessed by gel contraction assay (**Figure 2G-H**). Together, these data indicate that MCT expression and activity are required for myofibroblast differentiation *in vitro*. 

## MCT inhibition reprograms myofibroblast metabolism

MCTs are critical regulators of cellular lactate homeostasis. MCT1 is considered to be the main lactate importer in cells that use lactate to fuel oxidative phosphorylation or gluconeogenesis and is ubiquitously expressed. MCT1 also mediates lactate export in glycolytic cells [@halestrap2013; @brooks2018]. MCT4 is considered to be the main lactate exporter in glycolytic cells and is up-regulated by hypoxia-inducible transcription factors [@ullah2006; @halestrap2013]. MCT4 can also function as a lactate importer with a K~M~ ~1 mM [@contreras-baeza2019].

To evaluate the metabolic consequences of lactate transporter inhibition, we measured extracellular lactate in the conditioned medium from cells treated with MCT siRNA or pharmacologic inhibitors (**Figure 3A-B**). Silencing MCT1 and MCT4, separately or together, decreased TGFβ-stimulated lactate efflux in lung fibroblasts (**Figure 3A**). Silencing both transporters was required to block TGFβ-stimulated lactate efflux completely. By contrast, pharmacologic inhibition of either MCT1 or MCT4 did not decrease TGFβ-stimulated lactate efflux (**Figure 3B**), and inhibition of both transporters was required to decrease extracellular lactate. Similarly, inhibition of MCT1, MCT2, and MCT4 with the combination of AR-C155858 and VB124 was required to prevent increases in lactate efflux (**Supplemental Figure 3A**). Compared to lactate production, the effect of MCT inhibitors on extracellular glucose was less pronounced, although we did observe a trend toward decreased glucose consumption by cells treated with both AZD3965 and VB124 (**Supplemental Figure 3B**). These findings are consistent with prior studies suggesting compensatory roles for MCT1 and MCT4 in lactate export [@benjamin2018]. Moreover, these data also suggest that inhibition of glycolysis is not the mechanism by which lactate transport inhibition attenuates myofibroblast differentiation. 

To further interrogate the metabolic consequences of lactate transport inhibition, we next measured proton efflux (PER) and oxygen consumption (OCR) rates of lung fibroblasts treated with TGFβ in combination with MCT inhibitors (**Figure 3C, Supplemental Figure 3C**). Since MCTs co-transport protons with lactate, PER correlates with lactate efflux. Consistent with prior reports [@schruf2019; @cho2017; @xie2015; @bernard2015; @goodwin2018], we observed increases in both PER and OCR following TGFβ stimulation for 48 h, indicating increases in both glycolysis and oxidative phosphorylation. Similar to our direct measurements of extracellular lactate and glucose, simultaneous treatment with AZD3965 and VB124 was required to reduce PER. As anticipated, this decrease in PER was associated with a commensurate increase in OCR as myofibroblasts shifted their metabolism from glycolysis to oxidative phosphorylation. Unexpectedly, an increase in OCR was observed with AZD3965 and VB124 when administered individually. Indeed, the primary consequence of MCT1 or MCT4 inhibition alone was an increase in cellular ATP production rates driven by an increase in oxidative phosphorylation (**Figure 3D-E**). MCT inhibition decreased spare respiratory capacity, indicating that the basal respiratory rate of treated cells was closer to their maximal oxidative capacity (**Supplemental Figure 3D**). No significant differences in glycolytic capacity or electron transport chain coupling efficiency were observed (**Supplemental Figure 3D**). Together, these data suggest that the primary metabolic consequence of MCT inhibition is the activation of oxidative phosphorylation rather than inhibition of glycolysis. 

### YOU ARE HERE ###

To develop additional support for this hypothesis, we performed liquid chromatography-mass spectrometry-based profiling of intracellular and extracellular metabolites from cells treated with AZD3965 and VB124 to determine the impact of lactate transporter inhibition on metabolic pathways. 




Principal components (PC) analysis demonstrated excellent clustering of treatment groups with the drug effect corresponding to PC1 and the TGFβ treatment effect corresponding to PC2. Similar to the extracellular flux results described above, the magnitude of drug-induced perturbations were increased from MCT1 to MCT4 to combined inhibition (**Figure 4A**), as demonstrated by intracellular lactate levels (**Figure 4B**). As expected from measures of extracellular lactate following MCT inhibition, intracellular lactate accumulation increases modestly with MCT4 inhibition and markedly with MCT1/4 inhibition. TGFβ treatment was associated with diverse changes in the intracellular metabolomic profile of treated fibroblasts (**Supplemental Figure 4A-B**). The effect of AZD3965 alone on intracellular metabolite levels was modest (**Supplemental Figure 4C-D**). By contrast, MCT4 inhibition by VB124 alone (**Supplemental Figure 4E-F**) or combined with AZD3965 (**Figure 4C-D**) caused substantial perturbations to intracellular metabolism. Specifically, we observed enrichment of the glycolysis and tricarboxylic acid (TCA) cycle metabolite sets with MCT4 inhibition. Together, these data indicate that inhibition of lactate export leads to accumulation of upstream glycolytic intermediates that are rerouted to mitochondrial oxidative metabolic pathways. 

To test this hypothesis, we next labeled lung fibroblasts with [U-^13^C~6~]-glucose (8 mM)
in medium containing lactate (2 mM), glutamine (1 mM), and pyruvate (1 mM) during TGFβ stimulation and treatment with MCT inhibitors (**Figure 4E-F**). TGFβ increases ^13^C incorporation from glucose into pyruvate, lactate, citrate, succinate (SUC), and malate (MAL), consistent with increased flux from glucose into the TCA cycle. While AZD3965 had little impact on these labeling patterns, MCT4 inhibition significantly increased the fractions of these metabolites labeled by glucose, providing direct evidence for a proportional increase in glucose oxidation following MCT4 inhibition, consistent with the bioenergetic and steady-state metabolomics experiments described above. 

Increased metabolite labeling by glucose must by offset by decreased labeling from other substrates. Since recent data suggest that lactate is a major oxidative fuel source in lung [@hui2017; @hui2020], we reasoned that MCT inhibition would decrease oxidation of exogenous lactate. To test this, lung fibroblasts were cultured with [U-^13^C~3~]-lactate (2 mM) in medium containing naturally labeled glucose, glutamine, and pyruvate (**Figure 4F**). Notably, extracellular [U-^13^C~3~]-lactate labeled ~ 50% of intracellular pyruvate and lactate at baseline with significant downstream incorporation into TCA metabolites. This labeling was decreased following TGFβ treatment, mirroring increased fractional labeling from glucose. MCT inhibition had no impact on fractional labeling of TCA intermediates by [U-^13^C]-glutamine (**Supplemental Figure 4G**). Interestingly, MCT4 inhibition alone or combined with AZD3965 decreased ^13^C labeling of intracellular metabolites by lactate, emphasizing the importance of bi-directional lactate transport mediated by MCTs. Similar to our measurements of extracellular lactate, the effects of MCT inhibition were more pronounced when both inhibitors were used simultaneously, again demonstrating some functional redundancy of MCT1 and MCT4 in lung fibroblasts. 

\newpage

# Methods

\newpage

# Acknowledgements

# Conflicts of Interest

\newpage

# References

::: {#refs}
:::

\newpage

# Figures

![**Figure 1 - Lactate transporter expression increases in human IPF and experimental models.** (**A**) Immunoblot of whole lung homogenates from explanted IPF lungs and controls (Ctl). (**B**) Quantification of band densities from (A). (**C**) Immunoblot of whole lung homogenates from bleomycin (bleo)- and vehicle (Ctl)-treated mice. (**D**) Quantification of band densities from (C). (**E**) Representative immunoblot of cell lysates from normal human lung fibroblasts treated with TGFβ to induce myofibroblast differentiation. (**F**) Quantification of band densities from (E). Individual data points are biological replicates. Summary data are mean ± SEM (\* p < 0.05).](figs/Figure 01.png)

\newpage

![**Figure 2 - Lactate transport inhibition decreases myofibroblast differentiation *in vitro*.** (**A**) Representative immunoblot of normal lung fibroblast cell lysates after treatment with siRNA targeting MCT1 or MCT4. (**B**) Quantification of protein expression levels following MCT1 and MCT4 knockdown. (**C**) Immunoblot of IPF lung fibroblast lysates from three separate donors after treatment with TGFβ and MCT inhibitors AZD3965 (AZD) or VB124 (VB). (**D**) Quantification of band densities from (C). (**E**) Representative immunoblot of normal lung fibroblasts treated with TGFβ and MCT inhibitors. (**F**) Quantification of α-SMA expression following MCT inhibition. (**G**) Representative image of a gel contraction assay after 24 h treatment with TGFβ and MCT inhibitors. (**H**) Quantification of contracted areas. Individual data points are biological replicates. Summary data are mean ± SEM (\* p < 0.05; *black* compares TGFβ to control within a given treatment, *colored* compares the treatment effect to control for a given condition).](figs/Figure 02.png)
